[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
programs_voteon = "Be9tvYB3yTXbvqucYuGQQep2Cu4nE1ZXY9BsAvwguzu3"

[programs.devnet]
programs_voteon = "Be9tvYB3yTXbvqucYuGQQep2Cu4nE1ZXY9BsAvwguzu3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
